import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/date_symbol_data_local.dart';

import 'dart:async';
import 'package:flutter/services.dart';
import 'package:uni_links/uni_links.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

import 'login_screen.dart';
import 'home_screen.dart';
import 'onboarding_screen.dart';
import 'auth_service.dart';
import 'api_service.dart';
import 'family_service.dart';
import 'sync_service.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Ensure this file exists or will be generated by user

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await initializeDateFormatting('pt_BR', null);
  await SyncService.init(); // Initialize the offline Sync Service and Hive
  
  await SentryFlutter.init(
    (options) {
      options.dsn = const String.fromEnvironment('SENTRY_DSN', defaultValue: '');
      options.tracesSampleRate = 1.0; 
      options.attachStacktrace = true;
    },
    appRunner: () => runApp(const MyApp()),
  );
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return StreamBuilder(
      stream: AuthService().authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }
        if (snapshot.hasData) {
          // Usuário está logado, mas precisamos verificar o onboarding
          return const LoginRedirectHandler();
        }
        return const LoginScreen();
      },
    );
  }
}

class LoginRedirectHandler extends StatefulWidget {
  const LoginRedirectHandler({Key? key}) : super(key: key);

  @override
  State<LoginRedirectHandler> createState() => _LoginRedirectHandlerState();
}

class _LoginRedirectHandlerState extends State<LoginRedirectHandler> {
  @override
  void initState() {
    super.initState();
    _checkStatus();
  }

  Future<void> _checkStatus() async {
    try {
      final syncResponse = await ApiService.post('/users/sync', {});
      if (mounted) {
        if (syncResponse['onboarding_completed'] == true) {
          await FamilyService().fetchFamilies();
          Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const HomeScreen()));
        } else {
          Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const OnboardingScreen()));
        }
      }
    } catch (e) {
      debugPrint('Erro Crítico em _checkStatus() ao tentar sincrozinar com o Backend: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Falha ao sincronizar: $e'),
            duration: const Duration(seconds: 10),
            backgroundColor: Colors.red,
            action: SnackBarAction(label: 'Deslogar', textColor: Colors.white, onPressed: () async {
              await AuthService().signOut();
              if (mounted) {
                Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const LoginScreen()));
              }
            }),
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const CircularProgressIndicator(),
            const SizedBox(height: 16),
            const Text('Sincronizando seus dados...', style: TextStyle(color: Colors.grey)),
            const SizedBox(height: 24),
            TextButton(
               onPressed: () async {
                 await AuthService().signOut();
                 if (mounted) {
                   Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const LoginScreen()));
                 }
               }, 
               child: const Text('Cancelar e Voltar', style: TextStyle(color: Colors.red))
            )
          ]
        )
      )
    );
  }
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  StreamSubscription? _sub;
  final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

  @override
  void initState() {
    super.initState();
    initUniLinks();
  }

  @override
  void dispose() {
    _sub?.cancel();
    super.dispose();
  }

  Future<void> initUniLinks() async {
    try {
      final initialUri = await getInitialUri();
      _handleDeepLink(initialUri);
      
      _sub = uriLinkStream.listen((Uri? uri) {
        _handleDeepLink(uri);
      }, onError: (err) {
        debugPrint('Failed to handle incoming deep link: $err');
      });
    } on PlatformException {
      debugPrint('Failed to get initial link.');
    } on FormatException {
      debugPrint('Failed to parse the initial link as Uri.');
    }
  }

  void _handleDeepLink(Uri? uri) {
    if (uri == null) return;
    debugPrint("Deep Link Received: $uri");
    
    if (uri.path == '/finance') {
      // Just a fast route change demo for Deep Linking as requested by the plan.
      // Should redirect the user seamlessly when tapping notification using GoRouter etc.
      debugPrint("Deep Link routing requested for /finance");
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: navigatorKey,
      debugShowCheckedModeBanner: false,
      title: 'MEDIARE - MGCF',
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [Locale('pt', 'BR')],
      theme: ThemeData(
        useMaterial3: true,
        primaryColor: const Color(0xFF144BB8), // Deep soft blue
        scaffoldBackgroundColor: const Color(0xFFF8FAFC), // Very light gray/blue off-white
        colorScheme: const ColorScheme.light(
          primary: Color(0xFF144BB8),
          secondary: Color(0xFF489CE5), // Light pastel blue
          tertiary: Color(0xFF6EE7B7), // Mint green for success/accents
          error: Color(0xFFEF4444),
          surface: Colors.white,
          onPrimary: Colors.white,
          onSecondary: Colors.white,
          onError: Colors.white,
          onSurface: Color(0xFF1E293B), // Dark slate for text
        ),
        textTheme: GoogleFonts.plusJakartaSansTextTheme(
          Theme.of(context).textTheme,
        ).copyWith(
          displayLarge: const TextStyle(fontSize: 32, fontWeight: FontWeight.w800, color: Color(0xFF144BB8)),
          titleLarge: const TextStyle(fontSize: 22, fontWeight: FontWeight.bold, color: Color(0xFF1E293B)),
          bodyLarge: const TextStyle(fontSize: 16, color: Color(0xFF334155)),
          bodyMedium: const TextStyle(fontSize: 14, color: Color(0xFF64748B)),
        ),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFFF8FAFC),
          foregroundColor: Color(0xFF144BB8),
          elevation: 0,
          centerTitle: true,
          iconTheme: IconThemeData(color: Color(0xFF144BB8)),
          titleTextStyle: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Color(0xFF144BB8), fontFamily: 'Plus Jakarta Sans'),
        ),
        cardTheme: CardThemeData(
          color: Colors.white,
          elevation: 0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(24), // Squircles
            side: BorderSide(color: Colors.grey.withOpacity(0.1), width: 1),
          ),
          margin: const EdgeInsets.symmetric(vertical: 8, horizontal: 16),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF144BB8),
            foregroundColor: Colors.white,
            elevation: 0,
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 16),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
            textStyle: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
          ),
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: Colors.white,
          contentPadding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(color: Colors.grey.shade200),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: BorderSide(color: Colors.grey.shade200),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(16),
            borderSide: const BorderSide(color: Color(0xFF144BB8), width: 2),
          ),
        ),
        dialogTheme: DialogThemeData(
          backgroundColor: Colors.white,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
          titleTextStyle: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: Color(0xFF144BB8)),
        ),
      ),
      themeMode: ThemeMode.light, // Forçando light mode para a nova UI limpa
      home: const AuthWrapper(),
    );
  }
}